# This is the data i have created Randomly, Its is not any official data that gives the accurate results. But the method is same when you work on the real time data 

In [1]:
import pandas as pd

## Reading Data

In [2]:
df= pd.read_csv('data.csv')

In [3]:
df.head()

fever  bodypain  age  RunnyNose  Breath-Difficulty  CoronaVirus-Prob
0  101.381525         1   12          0                  1                 0
1   98.960883         0   44          0                  1                 0
2  101.264052         0    9          1                  0                 0
3  101.602270         1   50          1                 -1                 1
4  101.170900         1   79          0                  0                 1

In [4]:
df.tail()

fever  bodypain  age  RunnyNose  Breath-Difficulty  \
4140   98.119761         1   72          0                 -1   
4141  101.607165         1    9          1                 -1   
4142   99.692158         1   49          1                 -1   
4143   98.109358         1    8          0                  1   
4144  101.280613         0   54          1                 -1   

      CoronaVirus-Prob  
4140                 0  
4141                 1  
4142                 0  
4143                 0  
4144                 1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4145 entries, 0 to 4144
Data columns (total 6 columns):
fever                4145 non-null float64
bodypain             4145 non-null int64
age                  4145 non-null int64
RunnyNose            4145 non-null int64
Breath-Difficulty    4145 non-null int64
CoronaVirus-Prob     4145 non-null int64
dtypes: float64(1), int64(5)
memory usage: 194.4 KB


## Overview Of our Data in statistics

In [6]:
df.describe()

fever     bodypain          age    RunnyNose  Breath-Difficulty  \
count  4145.000000  4145.000000  4145.000000  4145.000000        4145.000000   
mean     99.959933     0.484680    50.461279     0.479131           0.006514   
std       1.166345     0.499826    28.846677     0.499625           0.817996   
min      98.000854     0.000000     1.000000     0.000000          -1.000000   
25%      98.938703     0.000000    25.000000     0.000000          -1.000000   
50%      99.957128     0.000000    51.000000     0.000000           0.000000   
75%     100.979363     1.000000    75.000000     1.000000           1.000000   
max     101.999990     1.000000   100.000000     1.000000           1.000000   

       CoronaVirus-Prob  
count       4145.000000  
mean           0.498432  
std            0.500058  
min            0.000000  
25%            0.000000  
50%            0.000000  
75%            1.000000  
max            1.000000

## Use Value Counts to check how much our data has variations

In [7]:
df['fever'].value_counts()

99.255018     1
101.394483    1
99.262998     1
99.231982     1
99.885885     1
             ..
99.155349     1
100.576107    1
99.959023     1
99.787785     1
98.132752     1
Name: fever, Length: 4145, dtype: int64

In [8]:
df['Breath-Difficulty'].value_counts()

 1    1400
-1    1373
 0    1372
Name: Breath-Difficulty, dtype: int64

In [9]:
df['CoronaVirus-Prob'].value_counts()

0    2079
1    2066
Name: CoronaVirus-Prob, dtype: int64

In [10]:
df['RunnyNose'].value_counts()

0    2159
1    1986
Name: RunnyNose, dtype: int64

In [11]:
df['bodypain'].value_counts()

0    2136
1    2009
Name: bodypain, dtype: int64

## Train Test Splitting

In [12]:
import numpy as np

In [13]:
def data_split(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indicies = shuffled[:test_set_size]
    train_indicies = shuffled[test_set_size:]
    return data.iloc[train_indicies], data.iloc[test_indicies]
    

In [14]:
train, test = data_split(df, 0.3)

In [15]:
train

fever  bodypain  age  RunnyNose  Breath-Difficulty  \
2554  101.672087         0   31          1                 -1   
4143   98.109358         1    8          0                  1   
2835  100.277265         0   13          0                 -1   
3161  100.010464         1   31          0                 -1   
2018   98.682562         0   34          1                  0   
...          ...       ...  ...        ...                ...   
3444   99.054576         0   93          0                  1   
466    99.434291         0   91          0                  1   
3092  100.560284         0   78          0                  1   
3772   99.370412         1   12          0                 -1   
860    98.237770         1   20          0                  0   

      CoronaVirus-Prob  
2554                 0  
4143                 0  
2835                 0  
3161                 1  
2018                 1  
...                ...  
3444                 0  
466                  0  
3092                 1  
3772                 0  
860                  1  

[2902 rows x 6 columns]

In [16]:
test

fever  bodypain  age  RunnyNose  Breath-Difficulty  \
3750  100.796048         0   48          0                  1   
1967  100.169370         1   51          0                  1   
1583   99.901686         0   20          1                 -1   
296   100.785687         0   27          0                  0   
149   101.363310         0   35          1                  0   
...          ...       ...  ...        ...                ...   
2909   99.975461         0   65          0                  0   
1451  101.079248         0    4          0                 -1   
1070   99.690770         0   92          1                  1   
3851   99.798630         0   42          1                  1   
4025  100.370304         0    7          1                 -1   

      CoronaVirus-Prob  
3750                 0  
1967                 0  
1583                 1  
296                  1  
149                  1  
...                ...  
2909                 1  
1451                 0  
1070                 0  
3851                 1  
4025                 1  

[1243 rows x 6 columns]

In [17]:
x_train = train[['fever', 'bodypain', 'age', 'RunnyNose', 'Breath-Difficulty']].to_numpy()
x_test = test[['fever', 'bodypain', 'age', 'RunnyNose', 'Breath-Difficulty']].to_numpy()

In [18]:
y_train = train[['CoronaVirus-Prob']].to_numpy().reshape(2902 ,)
y_test = test[['CoronaVirus-Prob']].to_numpy().reshape(1243,)

In [19]:
x_train

array([[101.6720871 ,   0.        ,  31.        ,   1.        ,
         -1.        ],
       [ 98.10935814,   1.        ,   8.        ,   0.        ,
          1.        ],
       [100.2772652 ,   0.        ,  13.        ,   0.        ,
         -1.        ],
       ...,
       [100.5602837 ,   0.        ,  78.        ,   0.        ,
          1.        ],
       [ 99.37041182,   1.        ,  12.        ,   0.        ,
         -1.        ],
       [ 98.23777042,   1.        ,  20.        ,   0.        ,
          0.        ]])

In [20]:
x_test

array([[100.7960485 ,   0.        ,  48.        ,   0.        ,
          1.        ],
       [100.1693695 ,   1.        ,  51.        ,   0.        ,
          1.        ],
       [ 99.90168613,   0.        ,  20.        ,   1.        ,
         -1.        ],
       ...,
       [ 99.69077006,   0.        ,  92.        ,   1.        ,
          1.        ],
       [ 99.79862986,   0.        ,  42.        ,   1.        ,
          1.        ],
       [100.3703036 ,   0.        ,   7.        ,   1.        ,
         -1.        ]])

In [21]:
y_train

array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

In [22]:
y_test

array([0, 0, 1, ..., 0, 1, 1], dtype=int64)

## So here we use the Logistic Regression To build the Model

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
lg = LogisticRegression()

In [25]:
lg.fit(x_train, y_train)

C:\Users\syedh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [26]:
df.head(3)

fever  bodypain  age  RunnyNose  Breath-Difficulty  CoronaVirus-Prob
0  101.381525         1   12          0                  1                 0
1   98.960883         0   44          0                  1                 0
2  101.264052         0    9          1                  0                 0

## Now we are going to check that our model is prediction right result or not? 

### We are giving the no  2 Record of head method. and it gives us the right result

In [27]:
lg.predict([[101.26, 0, 9, 1, 0]])

array([0], dtype=int64)

In [28]:
df.tail(3)

fever  bodypain  age  RunnyNose  Breath-Difficulty  \
4142   99.692158         1   49          1                 -1   
4143   98.109358         1    8          0                  1   
4144  101.280613         0   54          1                 -1   

      CoronaVirus-Prob  
4142                 0  
4143                 0  
4144                 1

In [29]:
lg.predict([[101.28, 0, 54, 1, -1]])

array([1], dtype=int64)

## Second prediction Is also right. So our model is trained Right 

In [30]:
lg.predict_proba([[101.28, 0, 54, 1, -1]])

array([[0.49211557, 0.50788443]])

# INPut Features

In [31]:
input_features = [101.28,0,54,1,-1]
result = lg.predict([input_features])

In [32]:
result

array([1], dtype=int64)